import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './layout.module.css'

export default function Layout({ children, home }) {
	return (
		<div className={styles.container}>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="header row">

				<div className="col-sm-6">
					<h1>
						<Link href="/">Monster Manager</Link>
					</h1>
				</div>

				<div className="col-sm-6">
					<ul className="nav nav-tabs nav nav-tabs navbar-right">
						<li>
							<Link href="/">Monster List</Link>
						</li>
						<li>
							<Link href="/manager" passHref>
								<>
									<a>View Encounter</a>
									<Image
										src="/images/wyvern.svg"
										alt="Monster Manager Logo"
										width={50}
										height={50}
									/>
									{/* <span>{encounter.length}</span> */}
								</>
							</Link>
						</li>
					</ul>
				</div>

			</div>
	
			<main className={styles.main}>
				<main>{children}</main>
			</main>
	
			<footer className={styles.footer}>
				<div className="footer row">

					<div className="bulilt-with col-sm-4">
						<p><strong>An interactive Dungeons and Dragons 5e Monster Manual built on React.js.</strong></p>
					</div>

					<div className="bulilt-with col-sm-4">
						<p>Some content used under the <a href="http://www.opengamingfoundation.org/ogl.html" target="_blank" title="Open Gaming License" rel="noreferrer">Open Gaming License.</a></p>
					</div>

					<div className="repo col-sm-4">
						<p><a href="https://github.com/gthayer/monster-manager" target="_blank" title="Contribute on GitHub" rel="noreferrer">Contribute on GitHub!</a></p>
					</div>

				</div>
			</footer>
	  </div>
	)
}