import Head from 'next/head'
import styles from './layout.module.css'
import Header from './header'
import Footer from './footer'

export default function Layout({ children, home }) {
	return (
		<div className={styles.container}>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header/>
	
			<main className={styles.main}>
				<main>{children}</main>
			</main>
	
			<Footer/>
	  </div>
	)
}