import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './layout.module.css'
import Header from './header'
import Footer from './footer'

export default function Layout({ children, home }) {
	return (
		<div className={styles.container}>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header/>

			<div className="grid grid-cols-2 gap-4">

				<h1>
					<Link href="/">Monster Manager</Link>
				</h1>

				<ul className="nav nav-tabs nav nav-tabs navbar-right">
					<li>
						<Link href="/">Monster List</Link>
					</li>
					<li>
						<Link href="/manager" passHref>
							<>
								<a>View Encounter</a>
								<Image
									src="/images/wyvern.svg"
									alt="Monster Manager Logo"
									width={50}
									height={50}
								/>
								{/* <span>{encounter.length}</span> */}
							</>
						</Link>
					</li>
				</ul>

			</div>
	
			<main className={styles.main}>
				<main>{children}</main>
			</main>
	
			<Footer/>
	  </div>
	)
}